import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal"],
});
const moniguedisplay = localFont({
  src: "../../public/fonts/MoniguedemoRegular-gwlL1.otf",
  variable: "--font-monigue-display",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable}  ${moniguedisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
