import React from "react";

function Card({ children }: { children: React.ReactNode }) {
  return (
    <div className="relative border border-dashed border-void/20 w-full max-w-sm lg:max-w-lg xl:max-w-[389.33px] aspect-square rounded-2xl lg:rounded-3xl p-3 lg:p-4">
      {children}
    </div>
  );
}

export default Card;
{
  /* <div class="flex items-center justify-center h-full"><div class="flex flex-col items-center justify-center w-full"><div class="flex flex-col items-center justify-center w-full gap-3 lg:gap-4 max-w-[140px] lg:max-w-[160px]"><div class="flex items-center justify-center w-full gap-2 lg:gap-3"><div class="bg-shell relative rounded-[1000px] shrink-0 w-12 h-12 lg:w-14 lg:h-14 xl:w-[59px] xl:h-[59px]"><div class="overflow-clip relative size-full"><div class="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2"><picture><img alt="RISC Zero" loading="lazy" width="33" height="23" decoding="async" data-nimg="1" class="block" style="color:transparent" src="/Images/risc-zero.svg"></picture></div></div><div aria-hidden="true" class="absolute border-[0.5px] border-void/[0.16] border-solid inset-0 pointer-events-none rounded-[1000px]"></div></div><div class="bg-shell relative rounded-[1000px] shrink-0 w-12 h-12 lg:w-14 lg:h-14 xl:w-[59px] xl:h-[59px]"><div class="overflow-clip relative size-full"><div class="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2"><picture><img alt="Noir" loading="lazy" width="33" height="23" decoding="async" data-nimg="1" class="block" style="color:transparent" src="/Images/noir.svg"></picture></div></div><div aria-hidden="true" class="absolute border-[0.5px] border-void/[0.16] border-solid inset-0 pointer-events-none rounded-[1000px]"></div></div><div class="bg-shell relative rounded-[1000px] shrink-0 w-12 h-12 lg:w-14 lg:h-14 xl:w-[59px] xl:h-[59px]"><div class="overflow-clip relative size-full"><picture><img alt="Succinct" loading="lazy" width="59" height="59" decoding="async" data-nimg="1" class="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2" style="color:transparent" src="/Images/succinct.svg"></picture></div><div aria-hidden="true" class="absolute border-[0.5px] border-void/[0.16] border-solid inset-0 pointer-events-none rounded-[1000px]"></div></div></div><div class="flex items-center justify-center gap-2 lg:gap-3"><div class="relative shrink-0 w-12 h-12 lg:w-14 lg:h-14 xl:w-[59px] xl:h-[59px]"><img alt="Space and Time" loading="lazy" width="59" height="59" decoding="async" data-nimg="1" class="block max-w-none size-full" style="color:transparent" src="/Images/space-and-time.svg"></div><div class="bg-shell relative rounded-[1000px] shrink-0 w-12 h-12 lg:w-14 lg:h-14 xl:w-[59px] xl:h-[59px]"><div class="overflow-clip relative size-full"><picture><img alt="Circom" loading="lazy" width="59" height="59" decoding="async" data-nimg="1" class="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2" style="color:transparent" src="/Images/circom.svg"></picture></div><div aria-hidden="true" class="absolute border-[0.5px] border-void/[0.16] border-solid inset-0 pointer-events-none rounded-[1000px]"></div></div></div></div></div></div></div> */
}
